
from torchtext.vocab import GloVe
import torch
from operator import itemgetter

def print_closest_words(glove, vec, n=5):
    dists = torch.norm(glove.vectors - vec, dim=1)     # compute distances to all words
    lst = sorted(enumerate(dists.numpy()), key=lambda x: x[1]) # sort by distance
    for idx, difference in lst[1:n+1]: 					       # take the top n
        print(glove.itos[idx], difference)

def closest_words_from_reference(reference='cat', other=None):
    other = [
        "dog",
        "garfield",
        "africa",
        "alley",
        "alleyway",
        "ally",
        "american home",
        "animal rescue shelter",
        "animal shops",
        "apartment",
        "appartment",
        "appartments",
        "arms",
        "arms of human",
        "art",
        "attic",
        "back alley",
        "back yard",
        "backyard",
        "bag",
        "barn",
        "basement",
        "be",
        "beam of sunlight",
        "bed",
        "bedroom",
        "best chair by fire",
        "box",
        "bushes",
        "cage",
        "canada",
        "canary cage",
        "car",
        "cartoon",
        "cat's basket",
        "cat box",
        "cat cannon",
        "cat litter tray",
        "cat lover's lap",
        "cat town",
        "catlover's home",
        "catnip",
        "cattery",
        "chair",
        "charge",
        "chinese restraunt",
        "chinese resturant",
        "clean laundry",
        "clean washing",
        "closet",
        "clothes basket",
        "comfortable chair",
        "comfortable position",
        "company of humans",
        "compost pile",
        "couch",
        "cream",
        "curled position",
        "desk",
        "dirt",
        "dmoz",
        "dog's mouth",
        "dogs mouth",
        "dumpsters",
        "family room",
        "favourite armchair",
        "field",
        "fight",
        "flat",
        "floor",
        "front door",
        "front of fireplace sleeping",
        "game",
        "grass",
        "ground",
        "hat comes back",
        "heat",
        "hiding",
        "home",
        "hose",
        "house",
        "houseplant",
        "human's lap",
        "humane shelter",
        "humane society",
        "istanbul streets",
        "it's basket",
        "jungle",
        "kid's picture book",
        "kitchen",
        "kitty litter bin",
        "lap",
        "laundry",
        "laundry basket",
        "lava pit",
        "lower brances of tree",
        "many peoples homes",
        "meat loaf",
        "microwave",
        "milky way galaxy",
        "nasty mood",
        "nature",
        "old lady's house",
        "outside",
        "own home",
        "owner's home",
        "paper bag",
        "park",
        "persons house",
        "pet stopre",
        "pet store home",
        "petshop",
        "petstore",
        "ranch",
        "relaxed position",
        "residence",
        "residential area",
        "roman colliseum",
        "rome",
        "roof",
        "rooftop",
        "rubbish bin",
        "rug",
        "sand box",
        "shelf",
        "show",
        "sigfried and roy performance",
        "sister in law's house",
        "sitting on chair",
        "sofa",
        "soft place",
        "soft sunny area",
        "spca",
        "spinster's house",
        "stir fried chicken",
        "story",
        "strangest places",
        "streets",
        "sun",
        "sunbeam",
        "sunny window",
        "sunny windowsill",
        "table",
        "texas",
        "toaster",
        "town",
        "trashcan",
        "trouble",
        "urban neighborhood",
        "urban settlement",
        "vet's examination room",
        "vet",
        "veterinarian's office",
        "warm bed",
        "warm place",
        "way",
        "weirdest places",
        "wild",
        "window sill",
        "windowsill",
        "woman's apartment",
        "zoo",
        "act finicky",
        "act irrational",
        "act nonchalant",
        "appear to angry",
        "case mouse",
        "cast shadow",
        "catch bird",
        "catch mouse",
        "catch rat",
        "chase mice",
        "chase tail",
        "clean face",
        "clean itself often",
        "clean themselves",
        "cleaning itself",
        "climb up tree",
        "corner mouse",
        "corner rat",
        "dream dream",
        "drink milk",
        "drink water",
        "eat bird",
        "eat cat food",
        "eat fish",
        "eat mice",
        "enjoy to take nap",
        "enjoy yogurt",
        "equal feline",
        "eye mouse",
        "fancy certain foods over others",
        "fight dog",
        "fish for fish",
        "fish with paw",
        "following mouse",
        "get mouse",
        "get wet",
        "guard kittens",
        "hear mouse near",
        "hide under bed",
        "hunt for mice",
        "hunt for mice in yard",
        "hunt lizards",
        "hunt mice",
        "jump much higher than height",
        "jump very well",
        "kill bird",
        "kill birds",
        "kill guinea pig",
        "kill mouse",
        "kill snake",
        "land on all four paws",
        "land upright",
        "laugh at king",
        "lie on mat",
        "lift mouse",
        "like tuna",
        "live long life",
        "live many years",
        "look at king",
        "look bird",
        "look out window",
        "meow",
        "mew",
        "miaow",
        "mother kits",
        "mother kittens",
        "nail man",
        "need meal",
        "note needs cleaning",
        "pet",
        "play with ball",
        "produce kittens",
        "rest all day",
        "ruling household",
        "run away",
        "scratch",
        "scratch furniture",
        "scratch if annoy",
        "scratch on scratching post",
        "see at night",
        "see in dark",
        "see king",
        "sit in window",
        "sleep",
        "sleep all day",
        "sleep long time",
        "sleep most of day",
        "sleep most of time",
        "sleep on windowsill",
        "stay downstairs",
        "stay inside house",
        "stay on lap",
        "sun itself",
        "sun on porch",
        "sun themselves in window",
        "touch leg",
        "trip old lady",
        "trip owner",
        "very good companion",
        "view king",
        "vomit",
        "vomit up dinner",
        "wait for rat",
        "walk down street",
        "walk on fence",
        "walk on top of car",
        "walk on windowsill",
        "wash itself",
        "wash itself with tongue",
        "wash paws",
        "watch mouse",
        "catamaran",
        "catfish",
        "control",
        "eat",
        "food",
        "food now",
        "have catnip",
        "milk",
        "milk to drink",
        "mouse",
        "nap",
        "nothing to do with",
        "petted",
        "stroked",
        "tuna fish",
        "warm place to live",
        "catt",
        "cat",
        "catta",
        "cattus",
        "kat",
        "catte",
        "قطة",
        "кот",
        "ϣⲁⲩ",
        "kòt",
        "cath",
        "katze",
        "t",
        "γατα",
        "catapult",
        "catastrophic",
        "methcathinone",
        "katu",
        "chat",
        "kaat",
        "kåt",
        "καττα",
        "chatz",
        "חתול",
        "կատու",
        "köttur",
        "kath",
        "kate",
        "katt",
        "katte",
        "kot",
        "cãtush",
        "resource",
        "wiki",
        "umbel",
        "wn31",
        "2012",
        "been shaved",
        "claws",
        "eyes",
        "four legs",
        "hair",
        "litter of kittens",
        "nose",
        "sharp claws",
        "sharp teeth",
        "whiskers",
        "ireland",
        "medicine",
        "argot",
        "vulgaire",
        "zoologie",
        "african american vernacular english",
        "nautical",
        "now only in catboat",
        "offensive",
        "slang",
        "vulgar",
        "computing",
        "military",
        "naval",
        "meat",
        "a",
        "difficult to wash in bath",
        "feline",
        "hungry",
        "mammal",
        "running after mouse",
        "thirsty",
        "acronym for computerized axial tomography",
        "animal",
        "bad luck sign",
        "charming manipulative pet",
        "dangerous too",
        "much loved pet",
        "natural hunter",
        "noun",
        "one type of animal",
        "quadriped",
        "small mammal",
        "talisman",
        "wonderful thing",
        "felis",
        "non person animal",
        "gossip",
        "woman",
        "book",
        "fur",
        "flog",
        "bath",
        "bathed",
        "chased by dog",
        "dog in house",
        "eat vegetables",
        "go into water",
        "live with dog",
        "run over by car",
        "sprayed with water",
        "tail pulled",
        "take bath",
        "washed",
        "wet",
        "wool sweater",
        "worming tablets",
        "attracted to parakeets",
        "kept in cage",
        "transported in box",
        "adult",
        "adult kitten",
        "animal feline",
        "big",
        "big kitten",
        "burmese",
        "catherine",
        "chase",
        "common",
        "common pet",
        "creature",
        "dog enemy",
        "dogs",
        "dogs chase",
        "dogs enemy",
        "domestic",
        "domestic animal",
        "domestic feline",
        "domestic pet",
        "domesticated",
        "domesticated animal",
        "eater",
        "eating",
        "eating rat",
        "enemy",
        "enemy dog",
        "feline animal",
        "feline creature",
        "feline pet",
        "felines",
        "four",
        "furry",
        "furry animal",
        "furry pet",
        "goes",
        "goes meow",
        "home animal",
        "homes",
        "house animal",
        "house pet",
        "house pets",
        "house tiger",
        "household",
        "household animal",
        "household feline",
        "household pet",
        "households",
        "houses",
        "killer",
        "kitten",
        "kittens",
        "kitty",
        "legs",
        "lion",
        "litter",
        "litter box",
        "lives",
        "maine coon",
        "manx",
        "meow animal",
        "meowing",
        "meowing pet",
        "meows",
        "mog",
        "mouse eater",
        "mouse enemy",
        "mouse killer",
        "mustaches",
        "nine",
        "nine lives",
        "panther",
        "pawed",
        "pawed animal",
        "paws",
        "persian",
        "pet animal",
        "pet mammal",
        "pets",
        "petting",
        "puma",
        "purr",
        "purring",
        "purring animal",
        "purring pet",
        "quick",
        "rat",
        "russian blue",
        "schrödinger’s cat",
        "siamese",
        "small",
        "small animal",
        "small dog",
        "small furry",
        "small lion",
        "soft",
        "tabby",
        "tail",
        "tiger",
        "disastrous",
        "terrible",
        "acetyltransferase",
        "chloramphenicol",
        "computed axial tomography",
        "computer aided translation",
        "chatte",
        "machine",
        "traduction assistée par ordinateur",
        "vagin",
        "vulve",
        "cat o nine tails",
        "cathead",
        "diminutive",
        "double",
        "felidae",
        "jazz",
        "plate",
        "prostitute",
        "tipcat",
        "trap and ball",
        "tripod",
        "vagina",
        "vulva",
        "unix",
        "caterpillar drive",
        "caterpillar track",
        "anchor",
        "hoist",
        "ring",
        "apply",
        "command",
        "dump",
        "ct",
        "feliform",
        "feline cat",
        "pantherine cat",
        "saber toothed cat",
        "computerized tomography",
        "big cat",
        "guy",
        "nostaa ankkuri",
        "caponner",
        "caponare",
        "being household pet",
        "catch mice",
        "companion to humans",
        "companionship",
        "delight child",
        "dust ceiling",
        "find comfort",
        "have pet",
        "keep feet warm",
        "keep mice away",
        "killing mice",
        "play with and make laugh",
        "small dictator",
        "novel"
    ]
    data = []
    for w in other:
        dist = torch.norm(glove[reference] - glove[w]).item()  # euclidean distance
        #print(w, float(dist))
        n_words = len(w.split(' '))
        data.append((w, dist, -n_words))
    sorted_data = sorted(data, key=itemgetter(2,1), reverse=False)[:30]
    print(sorted_data)

if __name__ == '__main__':
    examples = ['chip', 'baby', 'Beautiful']
    print("meow1")
    glove = GloVe(name='6B', dim=50)
    #ret = vec.get_vecs_by_tokens(examples, lower_case_backup=True)
    #print_closest_words(glove, glove["jump"], n=10)
    closest_words_from_reference()